#   This is goofy.
pipeline:
#   build:
#       image: python:2.7
#       commands:
#           - pip install -r requirements.txt
#           - python manage.py test

    ecr:
        image: plugins/ecr:1.0
        region: us-east-2
        repo: 224588347132.dkr.ecr.us-east-2.amazonaws.com/roma-test
        registry: 224588347132.dkr.ecr.us-east-2.amazonaws.com
        tags:
            - latest
            - ${DRONE_COMMIT}
            - ${DRONE_COMMIT_SHA}
