# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='author first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='author last name')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, unique=True, verbose_name='text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protoapp.Author')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('last_name', 'first_name')]),
        ),
    ]
